### ISSUE TITLE
Add icon for the snap

### ISSUE THREAD

**Issue by MonicaisHer** [canonical/edgex-ekuiper-snap#26]
The snapcraft.yaml maintains its metadata locally, rather than sourcing from [metadata](https://github.com/canonical/edgex-snap-metadata).

The current stable release in snapstore does not include an icon: https://snapcraft.io/edgex-ekuiper

**Comment by farshidtz** [comment]
Since https://github.com/canonical/edgex-ekuiper-snap/pull/50, the icon along with the other metadata are maintained on the store.
